# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "Maria's Blog"
tagline:          "Maria's Blog" #This is only used on pages with title "Home"
description:      "A Quantum Girl in a Quantum World"
url:              https://mraheb.github.io
baseurl:          jeslie0.github.io
sidebarimage:	  /images/pic.jpg
sidebarimagealttext:	It's me!

disqus:
   shortname:	disqus_H1rmibpPh5


author:
  name:           Maria Raheb
  url:            https://mraheb.github.io

plugins:
  - jekyll-paginate
  - jekyll-feed

# Sets blog page to have previews
paginate:         5
paginate_path: "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mraheb/mraheb.github.io

exclude:
  - Gemfile
  - Gemfile.lock


