# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Maria Raheb"
tagline:          "" #This is only used on pages with title "Home"
description:      "Be Slater <em>Determined</em>"
url:               https://mraheb.github.io
baseurl:          /
sidebarimage:	  /images/pic.jpg
sidebarimagealttext:	It's me!

disqus:
   shortname:	https-mraheb-github-io


author:
  name:           Maria Raheb
  url:            https://mraheb.github.io

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-last-modified-at

# Sets blog page to have previews
paginate:         5
paginate_path: "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mraheb/mraheb.github.io

exclude:
  - Gemfile
  - Gemfile.lock

last-modified-at:
    date-format: '%d-%b-%y'

